### ISSUE TITLE
CodeGeneration.Tests FAIL

### ISSUE THREAD

**Issue by ianbattersby** [ThatRendle/Simple.Web#27]
```
Simple.Web.CodeGeneration.Tests.HandlerRunnerBuilderTest.CallsPatchWithParameter [FAIL]
   Simple.Web.UnsupportedMediaTypeException : Requested type(s) not available
   Stack Trace:
      c:\Source\GitHub\Simple.Web\Simple.Web\Behaviors\Implementations\SetInput.cs(45,0): at Simple.Web.Behaviors.Implementations.GetInput.Impl[T](IContext context)
      at lambda_method(Closure , Object , IContext )
      c:\Source\GitHub\Simple.Web\Tests\Simple.Web.CodeGeneration.Tests\HandlerRunnerBuilderTest.cs(75,0): at Simple.Web.CodeGeneration.Tests.HandlerRunnerBuilderTest.CallsPatchWithParameter()
```

**Comment by ThatRendle** [comment]
Yes, I've been getting this. It appears to be a race condition or
something. Works fine if you run it individually. Under investigation.

**Comment by ianbattersby** [comment]
Interestingly this seems to be around `AppDomain.CurrentDomain.GetAssemblies()` (ExportedTypeHelper) consistently returning the appropriate `IMediaTypeHandler`. If you manually add the Type after the scan, it works every time, so perhaps it's not a straight-forward race-condition after all?

Hacky spike:-

```
    private static void PopulateContentTypeHandlerFunctions()
    {
        foreach (var exportedType in ExportedTypeHelper.FromCurrentAppDomain(TypeIsContentTypeHandler))
        {
            AddContentTypeHandler(exportedType);
        }

        AddContentTypeHandler(System.Reflection.Assembly.LoadFrom("..\\..\\..\\..\\Simple.Web.JsonFx\\bin\\debug\\Simple.Web.JsonFx.dll").GetExportedTypes().FirstOrDefault(x => x.Name == "JsonMediaTypeHandler"));
        AddContentTypeHandler(typeof(FormDeserializer));
    }
```

**Comment by ianbattersby** [comment]
Adding to my comment above, I'm not sure with this kind of type scanning if some kind of start-up object graph generation (via IoC container or otherwise) might be an option?

**Comment by ianbattersby** [comment]
Decided the [answers not in the box, it's in the band](https://github.com/markrendle/Simple.Web/pull/29) ;-)
